# Generated by Django 3.2.9 on 2021-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211114_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='pubDate',
            field=models.DateTimeField(),
        ),
    ]
