# Generated by Django 3.2.9 on 2021-11-14 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_newsitem_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='symbol',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
