# Generated by Django 3.2.9 on 2021-11-14 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newsitem_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='id',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
