# Generated by Django 3.2.9 on 2021-11-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211114_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='guid',
            new_name='id',
        ),
    ]
