# Generated by Django 3.2.9 on 2021-11-21 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_guid_newsitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
